name: Test CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print working directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Say hello
        run: echo "CI is working super fine! 🚀"

